### ISSUE TITLE
Does it work for queryparams?

### ISSUE THREAD

**Issue by therepo90** [lukeed/matchit#15]
```
let route = parse('/api/projects/:id/translations/add');
let url = '/api/projects/7/translations/add?group=true';
let matchObj = match(url, [route]);
console.log({matchObj})
if(matchObj.length){
	console.log('match');
	console.log(exec(url, matchObj));
}

```
it doesnt match

**Comment by lukeed** [comment]
It does, but you have to be working on the same terms. This is because `/foo` and `/foo?q=true` are two different URLs. You can tell matchit to parse a route pattern that contains a query, but that won't match non-query URLs & vice versa

```js
foo = parse('/foo/:bar/baz');
bar = parse('/foo/:bar/baz?q=1');

url1 = '/foo/1/baz';
url2 = '/foo/2/baz?q=1';

match(url1, [foo]).length > 0; //=> true
match(url2, [foo]).length > 0; //=> false

match(url1, [bar]).length > 0; //=> false
match(url2, [bar]).length > 0; //=> true
```

You pass in the thing to be parsed & the thing to be matched, so it's up to you to normalize the choice or at least know when one is wanted.

Personally, I always just use the pathname segments and then reach for the query params within the handler, when/if needed

Hope that helps!

**Comment by therepo90** [comment]
Yep, its just better not to specify queryparams in the url
