### ISSUE TITLE
url parse length

### ISSUE THREAD

**Issue by crazy4groovy** [lukeed/matchit#4]
Hi, neat lib!

A lot of libraries have a DoS vulnerability due to parsing times for very long inputs (ie url strings ~100K long).

I'm looking at https://github.com/lukeed/matchit/blob/master/lib/index.js#L19
and wondering if there's an issue here? Recursion stack overflow? Might be worth at least a benchmark test.

(I suppose the easiest solution is to cap the length at something reasonable like 1k)

**Comment by lukeed** [comment]
Hey, thanks~!

To be honest, I'm not really sure what you mean 🙈 But, if I understand correctly, I think that that logic belongs elsewhere, not inside the lib directly.

The reason for this is because `matchit.parse` requires a _pathname_, not the full URL, which means that some amount is parsing is required already. I think that validation-logic belongs in that step, not in the figure-out-what's-what step.

Does that sound fair?

**Comment by crazy4groovy** [comment]
You can see it here: https://medium.com/node-security/minimatch-redos-vulnerability-590da24e6d3c

The idea is just to limit the input size of the string being processed.

I'm not sure you want to leave this to developers who won't stop to think about this attack vector. But at the very least, you may want to test for it yourself; if you do see a performance choke then an informational warning on your README page would be better than nothing.

**Comment by ianwalter** [comment]
Does the vulnerability even apply since minimatch uses regex to match strings and matchit doesn't?

**Comment by crazy4groovy** [comment]
@ianwalter You're right, this issue no longer applies. Seems that the code has change a lot since Jan 24, as the link to source line is broken.

Can close this issue.
